"""empty message

Revision ID: 212e8dedb071
Revises: 699ec738a05f
Create Date: 2021-12-04 16:32:25.938965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212e8dedb071'
down_revision = '699ec738a05f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('join_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'join_date')
    # ### end Alembic commands ###
